// <auto-generated />
using System;
using HRCandidateManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRCandidateManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511165758_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CandidateSkill", b =>
                {
                    b.Property<int>("CandidatesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CandidatesId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("CandidateSkill", (string)null);

                    b.HasData(
                        new
                        {
                            CandidatesId = 1,
                            SkillsId = 1
                        },
                        new
                        {
                            CandidatesId = 1,
                            SkillsId = 2
                        },
                        new
                        {
                            CandidatesId = 1,
                            SkillsId = 3
                        },
                        new
                        {
                            CandidatesId = 1,
                            SkillsId = 4
                        },
                        new
                        {
                            CandidatesId = 2,
                            SkillsId = 2
                        },
                        new
                        {
                            CandidatesId = 2,
                            SkillsId = 3
                        },
                        new
                        {
                            CandidatesId = 2,
                            SkillsId = 5
                        },
                        new
                        {
                            CandidatesId = 3,
                            SkillsId = 1
                        },
                        new
                        {
                            CandidatesId = 3,
                            SkillsId = 4
                        },
                        new
                        {
                            CandidatesId = 3,
                            SkillsId = 6
                        },
                        new
                        {
                            CandidatesId = 4,
                            SkillsId = 7
                        },
                        new
                        {
                            CandidatesId = 4,
                            SkillsId = 8
                        },
                        new
                        {
                            CandidatesId = 5,
                            SkillsId = 2
                        },
                        new
                        {
                            CandidatesId = 5,
                            SkillsId = 7
                        });
                });

            modelBuilder.Entity("HRCandidateManagement.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "+1234567890",
                            DateOfBirth = new DateOnly(1990, 5, 15),
                            Email = "john.smith@example.com",
                            FullName = "John Smith"
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "+1234567891",
                            DateOfBirth = new DateOnly(1992, 8, 22),
                            Email = "jane.doe@example.com",
                            FullName = "Jane Doe"
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "+1234567892",
                            DateOfBirth = new DateOnly(1988, 3, 10),
                            Email = "michael.johnson@example.com",
                            FullName = "Michael Johnson"
                        },
                        new
                        {
                            Id = 4,
                            ContactNumber = "+1234567893",
                            DateOfBirth = new DateOnly(1995, 11, 30),
                            Email = "emily.brown@example.com",
                            FullName = "Emily Brown"
                        },
                        new
                        {
                            Id = 5,
                            ContactNumber = "+1234567894",
                            DateOfBirth = new DateOnly(1991, 7, 7),
                            Email = "david.wilson@example.com",
                            FullName = "David Wilson"
                        });
                });

            modelBuilder.Entity("HRCandidateManagement.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 2,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Database Design"
                        },
                        new
                        {
                            Id = 4,
                            Name = "English"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Russian"
                        },
                        new
                        {
                            Id = 6,
                            Name = "German"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 8,
                            Name = "SQL"
                        });
                });

            modelBuilder.Entity("CandidateSkill", b =>
                {
                    b.HasOne("HRCandidateManagement.Models.Candidate", null)
                        .WithMany()
                        .HasForeignKey("CandidatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRCandidateManagement.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
